### ISSUE TITLE
통신 방식(Polling/Long Polling/Streaming) 자료조사

### ISSUE THREAD

**Issue by llcodingll** [hk-toss-full/spring-study#11]

**Comment by JoGyoungJun** [comment]
### Polling, Long Polling, Streaming에 대한 상세 정리

1. **Polling**

- **특징**: 클라이언트가 일정한 주기로 서버에 요청을 보내 데이터를 받아오는 방식. 
서버는 클라이언트의 요청이 있을 때만 현재 상태를 응답하며,
 클라이언트는 반복적으로 요청을 보내야 함. 
 서버에 데이터가 변경되지 않아도 클라이언트가 계속 요청을 보내므로 서버 자원 낭비가 발생할 수 있음.

- **장점**: 구현이 간단하며, HTTP 요청/응답 패턴을 그대로 사용하므로 설정이 쉬움.

- **단점**: 서버에 불필요한 요청이 많아지고, 지연 시간이 발생할 수 있음.

- **사용처**: 데이터 변화가 자주 발생하지 않거나, 간헐적으로 업데이트가 필요한 경우 적합. 예: 주기적인 상태 체크 기능.

---

2. **Long Polling**

- **특징**: 클라이언트가 서버에 요청을 보낸 후, 
 서버에서 새로운 데이터가 준비될 때까지 연결을 유지함. 
 새로운 데이터가 준비되면 서버가 응답하고, 클라이언트는 다시 요청을 보냄. 
 일반 Polling과 달리, 서버가 새로운 데이터가 생길 때만 응답하기 때문에 서버 자원의 낭비를 줄일 수 있음.

- **장점**: 실시간에 가까운 데이터를 제공하면서도 서버 자원을 효율적으로 사용할 수 있음.

- **단점**: 서버와 클라이언트 간 연결을 오래 유지하므로, 서버의 연결 수 제한에 도달할 위험이 있음. HTTP 연결이 오래 유지되므로 방화벽이나 프록시에서 타임아웃 문제가 발생할 수 있음.

- **사용처**: 실시간성이 필요한 웹 애플리케이션에서 웹소켓을 사용하기 어려운 경우. 예: 채팅 애플리케이션, 알림 시스템.

---

3. **Streaming**

- **특징**: 서버와 클라이언트 간 지속적인 연결을 유지하고, 
 서버에서 데이터가 발생하는 즉시 클라이언트로 스트림 형태로 전송. 
 연결이 한 번 설정되면 여러 개의 데이터 조각을 끊임없이 클라이언트에게 전달함.

- **장점**: 실시간으로 데이터를 전달하므로, 지연 시간이 매우 짧고 즉각적인 반응이 가능함. 연결이 지속되기 때문에 데이터를 빠르게 전송 가능.

- **단점**: 지속적인 연결을 유지하기 때문에 서버 리소스를 많이 사용하며, 연결이 끊어지면 재연결이 필요함. 네트워크 상태가 좋지 않을 경우 끊김 현상이 발생할 수 있음.

- **사용처**: 실시간 업데이트가 필요한 경우. 예: 주식 거래 시스템, 스포츠 경기 결과 업데이트, 미디어 스트리밍.

**Comment by seyeon326** [comment]
## Polling 동작 방식
1. 클라이언트가 주기적으로 서버에 요청을 보냄
2. 서버는 요청을 받고, 현재 상태(데이터)를 확인
3. 서버가 데이터가 변경되었는지 여부에 따라 응답을 보냄
4. 클라이언트는 응답을 받고, 필요한 경우 UI를 업데이트
5. 이 과정을 주기적으로 반복

예) 클라이언트가 5초마다 서버에 GET 요청을 보내 새로운 뉴스 기사를 확인하는 경우

<hr/>

## Long Polling 동작 방식
1. 클라이언트가 서버에 요청을 보냄
2. 서버는 즉시 응답하지 않고, 데이터가 준비될 때까지 대기
3. 데이터가 준비되면 서버가 클라이언트에 응답
4. 클라이언트는 응답을 받고 필요한 작업(예: UI 업데이트)을 수행
5. 클라이언트는 다시 서버에 새로운 요청을 보내어 이 과정을 반복

예) 채팅 애플리케이션에서 클라이언트가 메시지를 기다리며 요청을 보내고, 서버가 새로운 메시지가 도착하면 응답하는 경우

<hr/>

## Streaming 동작 방식
1. 클라이언트가 서버에 연결을 요청 (예: WebSocket 연결)
2. 서버가 클라이언트의 연결 요청을 수락하고, 양방향 연결이 설정됨
3. 클라이언트와 서버는 이 연결을 통해 데이터를 실시간으로 주고받고, 데이터가 발생하면 즉시 전송됨
4. 연결이 유지되는 동안, 클라이언트와 서버는 언제든지 데이터를 전송할 수 있음
5. 통신이 끝나면 클라이언트나 서버가 연결을 닫음

예) 온라인 게임, 실시간 주식 거래 애플리케이션, 또는 WebSocket을 사용하는 채팅 서비스에서 데이터가 실시간으로 전송되는 경우

**=> 소켓을 사용할 때, 통신 방식으로는 Streaming이 가장 적합함**

<hr/>

## 차이점 정리

![Image](https://github.com/user-attachments/assets/1976aa54-2b53-4dce-8c21-160e1ff0ab7c)

**Comment by llcodingll** [comment]
Polling (폴링)

1.	클라이언트가 주기적으로 서버에 요청을 보내는 방식.
예시: 뉴스 앱이 5초마다 서버에 새 기사가 있는지 확인하는 상황.
2.	서버는 클라이언트의 요청을 받고, 데이터가 바뀌었는지 확인함.
3.	새로운 기사가 있으면 서버가 응답하고, 없으면 그대로 응답.
4.	클라이언트는 응답을 받고 새 기사가 있으면 화면을 업데이트.
5.	이 과정을 계속 반복함.
장점: 간단함.
단점: 서버에 자주 요청을 보내야 하므로 비효율적일 수 있음.

Long Polling (롱 폴링)

1.	클라이언트가 서버에 요청을 보낸 후 서버가 바로 응답하지 않고 기다리는 방식.
예시: 채팅 앱에서 새 메시지를 기다리는 상황.
2.	서버는 새 메시지가 도착할 때까지 대기함.
3.	새 메시지가 도착하면 서버가 클라이언트에 응답을 보냄.
4.	클라이언트는 새 메시지를 받아 화면에 표시.
5.	클라이언트는 다시 서버에 요청을 보내며 이 과정을 반복함.
장점: 폴링보다 서버에 불필요한 요청을 줄일 수 있음.
단점: 대기 시간이 길어질 수 있음.

Streaming (스트리밍)

1.	클라이언트가 서버에 연결을 요청하고, 서버가 연결을 수락하여 양방향 통신이 가능한 상태가 됨.
예시: 온라인 게임에서 플레이어의 움직임이 실시간으로 전송되는 상황.
2.	서버와 클라이언트는 데이터를 실시간으로 주고받음.
3.	게임 내에서 움직이거나 이벤트가 발생할 때마다 그 데이터가 즉시 전송됨.
4.	통신이 끝나기 전까지 연결은 계속 유지됨.
장점: 실시간 데이터 전송이 가능함.
단점: 연결이 끊기면 다시 연결을 설정해야 함.

차이점 요약

- Polling: 클라이언트가 일정 주기로 서버에 “새 소식 있어?“라고 물어보는 것.
예시: 뉴스 앱이 5초마다 새 기사를 확인하는 경우.
- Long Polling: 클라이언트가 “새 소식 있을 때까지 기다릴게”라고 말하고, 서버가 데이터가 준비되면 응답하는 방식.
예시: 채팅 앱에서 새 메시지를 기다리는 경우.
- Streaming: 클라이언트와 서버가 “계속 연결되어 있으니, 실시간으로 데이터 주고받자” 하는 방식.
예시: 온라인 게임이나 실시간 주식 거래 앱에서 데이터를 실시간으로 주고받는 경우.
