### ISSUE TITLE
[spring-team1] gRPC 자료조사

### ISSUE THREAD

**Issue by seunzu** [hk-toss-full/spring-study#6]

**Comment by seunzu** [comment]
https://0123suh.notion.site/gRPC-11f86c5edd3f809c91a7ec6d28aa9f7b?pvs=74

**Comment by sulwon** [comment]
[gRPC.pdf](https://github.com/user-attachments/files/17362724/gRPC.pdf)

**Comment by G0sim** [comment]
https://crystal-closet-cd5.notion.site/gRPC-11fb49034c0880ee92f2f7b480581d94?pvs=4

**Comment by hyeonjeong9911** [comment]
https://pyrite-latency-af9.notion.site/gRPC-Google-Remote-Procedure-Call-11f4c7f10be480b5819adbc706609caf?pvs=4
