### ISSUE TITLE
[spring-team1] MyBatis 자료조사

### ISSUE THREAD

**Issue by seunzu** [hk-toss-full/spring-study#7]

**Comment by seunzu** [comment]
https://0123suh.notion.site/MyBatis-11f86c5edd3f80c7acd2c78a5919d6d1?pvs=4

**Comment by sulwon** [comment]
[MyBatis.pdf](https://github.com/user-attachments/files/17362105/MyBatis.pdf)

**Comment by hyeonjeong9911** [comment]
https://pyrite-latency-af9.notion.site/MyBatis-11f4c7f10be480c49a0addac24d69f97?pvs=4

**Comment by G0sim** [comment]
https://crystal-closet-cd5.notion.site/MyBatis-11fb49034c0880b39d78c4da65d884aa?pvs=4
