### ISSUE TITLE
Query DSL 자료조사

### ISSUE THREAD

**Issue by bbungjin** [hk-toss-full/spring-study#8]

**Comment by qwerasdfxzdcv** [comment]
Query DSL (Domain-Specific Language)는 Elasticsearch에서 데이터를 검색하기 위한 구조화된 JSON 기반 언어로, 매우 유연하고 복잡한 검색 쿼리를 구성할 수 있게 해준다. Query DSL은 크게 두 가지로 나눌 수 있다.

1.쿼리 컨텍스트 (Query Context): 검색의 정확도를 조정하는 데 사용됩니다. 이 컨텍스트에서 쿼리는 문서의 점수를 계산하여 문서가 얼마나 일치하는지에 따라 정렬된 결과를 반환합니다.
1.필터 컨텍스트 (Filter Context): 문서를 걸러내기 위한 조건을 설정하며, 필터는 점수를 계산하지 않고 단순히 조건에 맞는 문서를 포함하거나 제외합니다.

Query DSL 주요 유형

- Match 쿼리

> 주어진 텍스트를 분석하여 문서를 검색하는 데 사용, 기본적으로 자연어를 분석하기 때문에, 단어 형태소 분석이나 동의어 검색 등을 할 수 있음

```
{
  "query": {
    "match": {
      "content": "Elasticsearch basics"
    }
  }
}
//content 필드에서 "Elasticsearch basics"를 포함한 문서를 검색
```

- Term 쿼리
> 분석되지 않은 단어를 그대로 검색, 텍스트가 정확히 일치해야 함

```
{
  "query": {
    "term": {
      "status": "published"
    }
  }
}
//stauts 필드에서 "published"와 정확히 일치하는 문서를 검색
```

- Range 쿼리
> 숫자나 날짜 범위를 설정하여 검색

```
{
  "query": {
    "range": {
      "publish_date": {
        "gte": "2023-01-01",
        "lte": "2023-12-31"
      }
    }
  }
}
// publish_date가 2023년인 문서를 검색
```

- Bool 쿼리
>여러 쿼리를 조합하여 논리 연산을 수행할 수 있음, 조건을 사용하여 보다 복잡한 검색을 할 수 있음(must, should, must_not 등)


```
{
  "query": {
    "bool": {
      "must": [
        { "match": { "title": "Elasticsearch" } },
        { "range": { "publish_date": { "gte": "2022-01-01" } } }
      ],
      "must_not": [
        { "term": { "status": "draft" } }
      ],
      "should": [
        { "match": { "author": "John" } }
      ]
    }
  }
}
```
must: 이 조건을 만족하는 문서만 반환합니다 (AND 조건).
should: 이 조건을 만족하면 점수가 더 높아집니다 (OR 조건).
must_not: 이 조건을 만족하지 않는 문서를 반환합니다 (NOT 조건).

- Aggregations (집계)
>데이터를 분석하고 통계를 구하는 데 사용

```
{
  "aggs": {
    "status_count": {
      "terms": {
        "field": "status"
      }
    }
  }
}
//status 필드의 각 값에 대해 문서의 개수 집계
```

- Nested 쿼리
>중첩된 객체에 대해 검색을 수행

```
{
  "query": {
    "nested": {
      "path": "comments",
      "query": {
        "bool": {
          "must": [
            { "match": { "comments.text": "great" } },
            { "term": { "comments.author": "John" } }
          ]
        }
      }
    }
  }
}
```

**Comment by bbungjin** [comment]
https://spiny-dedication-748.notion.site/Query-DSL-11f68897439480ce9053ea8e87f3ad4b?pvs=4
