### ISSUE TITLE
socket 자료조사

### ISSUE THREAD

**Issue by llcodingll** [hk-toss-full/spring-study#9]

**Comment by JoGyoungJun** [comment]
**1. 양방향 통신 가능**

소켓을 통해 데이터를 송신과 수신 모두 할 수 있어, 
클라이언트와 서버 간에 양방향 통신이 가능 
이로 인해 실시간 데이터 전송이나 대화형 애플리케이션에 매우 적합

**2. 연결 지향적 소켓 (TCP)**

TCP 소켓은 연결 지향적이며, 
이는 클라이언트와 서버가 연결을 설정한 후, 
안정적인 데이터 전송을 보장하는 통신 방식 
데이터가 손실되면 재전송되고, 전송 순서가 유지되므로 신뢰성 있는 통신이 가능

* 특징: 데이터 전송의 신뢰성 보장, 흐름 제어, 오류 제어.

**3. 비연결 지향적 소켓 (UDP)**

UDP 소켓은 비연결 지향적 이며,
클라이언트와 서버 간에 연결을 설정하지 않고, 데이터를 빠르게 전송할 수 있다. 
데이터 전송 순서나 손실에 대한 보장은 없지만, 속도가 매우 빠르기 때문에 
스트리밍, 온라인 게임 등에서 많이 사용됨

* 특징: 신속한 데이터 전송, 신뢰성 낮음, 오류 제어 없음.

**4. 저수준 통신**

소켓은 네트워크 통신에서 비교적 저수준의 API로, 데이터를 패킷 단위로 전송 
네트워크의 세부적인 동작을 제어할 수 있으며, 
네트워크 프로그래밍의 기초가 되는 기술 
개발자는 이를 통해 전송 프로토콜(TCP, UDP 등), 포트 번호, IP 주소 등을 직접 관리할 수 있다.

**5. 포트와 결합**

소켓은 특정 포트 번호와 결합되어, 서버와 클라이언트가 데이터를 주고받는 특정 네트워크 서비스나 애플리케이션을 나타낸다.
예를 들어, HTTP 통신은 보통 포트 80, HTTPS는 포트 443을 사용

**6. IP 주소와 결합**

소켓은 IP 주소와 연결되며, 인터넷상에서 컴퓨터나 장치를 식별하는 고유 주소로, 
클라이언트와 서버가 통신할 때 각 소켓이 서로를 식별하고 데이터를 전송하는 데 사용

**7. 동시성 처리**

여러 클라이언트가 동일한 서버와 통신할 수 있으며, 
서버는 멀티스레딩, 비동기 I/O 등을 사용하여 동시성 처리를 지원 
여러 사용자가 동시에 소켓을 열어도, 서버는 각 사용자와 독립적으로 데이터를 주고받을 수 있다.

**8. 데이터 스트림 기반 (TCP)**

TCP 소켓의 경우, 데이터 스트림 기반으로 동작하며,  
데이터를 연속적으로 흐르게 하여 패킷 단위가 아닌 바이트 스트림으로 처리 
이로 인해 송수신되는 데이터의 크기에 관계없이 연결을 유지하면서 연속적인 데이터를 주고받을 수 있다.

**9. 비동기 통신**

소켓은 비동기 방식으로 데이터를 전송할 수 있으며, 
클라이언트가 데이터를 보내는 동안 다른 작업을 할 수 있다. 
비동기 소켓은 서버가 즉시 응답하지 않더라도 클라이언트는 대기하지 않고 다른 작업을 계속할 수 있다.

**10. 다양한 프로토콜 지원**

소켓은 다양한 네트워크 프로토콜을 지원 
TCP와 UDP가 가장 많이 사용되지만,  
HTTP, FTP, SMTP와 같은 여러 상위 레벨의 프로토콜도 소켓 기반에서 동작

**11. 오류 처리**

소켓 통신은 네트워크 환경에서 발생할 수 있는 다양한 오류 처리를 지원 
연결 실패, 타임아웃, 패킷 손실 등의 상황에서 오류 메시지를 반환하고, 
이를 통해 네트워크의 안정성을 관리할 수 있다.

**Comment by seyeon326** [comment]
# HTTP 통신과 소켓 통신의 차이
## HTTP 통신
- 클라이언트의 **요청이 있을 때만** 서버가 응답
- JSON, HTML, Image 등 다양한 데이터를 주고 받을 수 있음
- **서버가 응답한 후 연결을 바로 종료**하는 단방향 통신이지만 Keep Alive 옵션을 주어 일정 시간동안 커넥션을 유지할 수 있다.
- 실시간 연결이 아닌 데이터 전달이 필요한 경우에만 요청을 보내는 상황에 유리

## 소켓 통신
- 클라이언트와 서버가 특정 포트를 통해 **양방향 통신**을 하는 방식
- 데이터 전달 후 연결이 끊어지는 것이 아니라 **계속해서 연결을 유지** → HTTP에 비해 더 많은 리소스 소모
- 클라이언트와 서버가 실시간으로 계속하여 데이터를 주고 받아야 하는 경우에 유리
- 실시간 동영상 스트리밍, 온라인 게임, 채팅 등에 사용

<hr/>

# 소켓 통신 프로토콜
## TCP
- `SOCK_STREAM` 타입으로 생성되며, 연결 지향적이고 신뢰성을 제공
- 데이터가 순서대로 도착하고 손실이 발생하지 않도록 보장
- 웹 브라우징(HTTP/HTTPS), 이메일(SMTP, IMAP), 파일 전송(FTP) 등 중요한 데이터를 주고받는 상황에서는 TCP가 더 적합

## UDP
- `SOCK_DGRAM` 타입으로 생성되며, 비연결 지향적
- 데이터 전송 속도가 빠르지만, 신뢰성이나 순서 보장은 하지 않음
- 온라인 게임, 음성 통화 등 실시간성이나 속도가 중요한 경우에는 UDP가 더 유리할 수 있음

<hr/>

# 일반적인 소켓 통신의 흐름

![Image](https://github.com/user-attachments/assets/75cbef10-45e2-4a03-96f9-c34dae8758c9)

### 서버
1. 소켓 생성
2. 바인딩 (ip, port번호 설정)
3. listen()으로 클라이언트 요청에 대기열을 만들어 몇개의 클라이언트를 대기시킬지 결정
4. accept()로 클라이언트와 연결
5. 데이터 송수신
6. 소켓 닫기

### 클라이언트
1. 소켓 생성
2. 서버에 설정된 ip, port로 연결 시도
3. accept()로 클라이언트의 socket descriptor 반환
4. 데이터 송수신
5. 소켓 닫기

**Comment by llcodingll** [comment]
1.	양방향 통신
카카오톡처럼 서버와 클라이언트가 서로 데이터를 주고받는 구조. 예를 들어, 메시지를 실시간으로 주고받는 대화형 애플리케이션에 적합함.
2.	연결 지향 소켓 (TCP)
택배를 보내는 과정과 비슷한 개념. 데이터가 정확하게 도착하는지 확인하고, 문제가 있으면 다시 보내는 구조. 예를 들어, 웹사이트에서 파일 다운로드 시 안정성을 보장함.
3.	비연결 지향 소켓 (UDP)
엽서를 보내는 것과 비슷한 개념. 빠르게 데이터를 보내지만, 손실이나 순서가 바뀔 가능성이 있음. 예를 들어, 온라인 게임에서 빠른 데이터 전송이 필요할 때 사용됨.
4.	저수준 통신
전화를 직접 걸어서 통화하는 것처럼, 네트워크의 세부 동작을 개발자가 직접 관리하는 방식. 포트 번호나 IP 주소 등을 설정하는 작업이 포함됨.
5.	포트와 연결
집 주소처럼 포트를 통해 특정 서비스를 식별하는 방식. 예를 들어, 웹사이트 접속 시 포트 80(HTTP)이나 443(HTTPS)을 사용함.
6.	IP 주소와 연결
집 주소를 통해 친구에게 편지를 보내는 것처럼, IP 주소를 사용해 장치를 식별하고 데이터를 주고받는 방식.
7.	동시성 처리
채팅방에서 여러 사람이 동시에 메시지를 주고받는 상황과 비슷한 구조. 서버는 멀티스레딩을 사용해 여러 사용자의 요청을 동시에 처리함.
8.	데이터 스트림 기반 (TCP)
긴 편지를 여러 장으로 나눠서 보내는 방식. TCP 소켓은 데이터를 끊임없이 연결된 스트림 형태로 전송해 안정적인 통신을 보장함.
9.	비동기 통신
파일을 업로드하면서 다른 작업을 하는 것처럼, 데이터를 전송하는 동안 다른 작업을 동시에 처리할 수 있는 구조.
10.	다양한 프로토콜 지원
웹사이트 접속, 파일 전송, 이메일 전송 등 다양한 네트워크 프로토콜을 지원하는 구조. 예를 들어, HTTP, FTP, SMTP 같은 프로토콜을 사용함.
11.	오류 처리
연결이 끊기거나 데이터가 손실될 때 이를 자동으로 감지하고 오류 메시지를 반환하는 구조. 예를 들어, 인터넷 연결이 불안정할 때 재연결 시도와 같은 오류 관리 기능이 있음.
